import { Groups } from '../types/groups.enum';
import { ArtistDiscography } from '../types/release.interface';

export const discography: ArtistDiscography[] = [
  {
    creditedAs: "Nick Harris",
    releases: [
      {
        title: "PAPA DOUBLE ALBUM",
        artist: Groups.YMIAH,
        year: 2025,
        image: "/discog-images/papa-double-album.jpg",
        format: "2xFile, FLAC, Single",
        label: "Not On Label (Self-released)",
        role: "Appearance",
      },
      {
        title: "La Sagrada Familia b/w I Can't Love You",
        artist: Groups.LK,
        year: 2025,
        image: "/discog-images/la-sagrada.jpg",
        format: "2xFile, FLAC, Single",
        label: "Not On Label (Self-released)",
        role: "Appearance",
      },
      {
        title: "PAY ATTENTION PAY ATTENTION",
        artist: Groups.YMIAH,
        year: 2025,
        image: "/discog-images/pay-attention.jpg",
        format: "2xFile, FLAC, Single",
        label: "Not On Label (Self-released)",
        role: "Appearance",
      },
      {
        title: "🕴 🚬",
        artist: Groups.YMIAH,
        year: 2024,
        image: "/discog-images/man-levitating-emoji-with-cigarett-ymiah.jpg",
        format: "2xFile, FLAC, Single",
        label: "Not On Label (Self-released)",
        role: "Appearance",
      },
      {
        title: "I Don't Want To Get Adjusted To This World",
        artist: Groups.SteveSlagg,
        year: 2024,
        image: "/discog-images/dont-want-to-get-adjusted.jpg",
        format: "2xFile, FLAC, Single",
        label: "Not On Label (Steve Slagg Self-released)",
        role: "Appearance",
      },
      {
        title: "Actor Brought a Vice",
        artist: Groups.YMIAH,
        year: 2023,
        image: "/discog-images/actor-brought-a-vice.jpg",
        format: "2xFile, FLAC, Single",
        label: "Not On Label (Self-released)",
        role: "Appearance",
      },
      {
        title: "Other People",
        artist: Groups.YMIAH,
        year: 2022,
        image: "/discog-images/other-people.jpg",
        format: "File, MP3, Album",
        label: "Not On Label",
        role: "Appearance",
      },
      {
        title: "Neé Robert EP",
        artist: Groups.YMIAH,
        year: 2021,
        image: "/discog-images/nee-robert-ep.jpg",
        format: "File, MP3, EP",
        label: "Not On Label",
        role: "Appearance",
      },
      {
        title: "God Bless Meyer Horn EP",
        artist: Groups.YMIAH,
        year: 2021,
        image: "/discog-images/god-bless-meyer-horn.jpg",
        format: "File, MP3, EP",
        label: "Not On Label",
        role: "Appearance",
      },
      {
        title: "Jarvis",
        artist: Groups.YMIAH,
        year: 2020,
        image: "/discog-images/jarvis.jpg",
        format: "12\", Ltd + File, MP3",
        label: "Coach House Sounds",
        role: "Appearance",
      },
      {
        title: "The Alternate Universe of Love",
        artist: Groups.MOONER,
        year: 2020,
        image: "/discog-images/the-alternate-universe-of-love.jpg",
        format: "File, MP3, Album",
        label: "Aerial Ballet Records",
        role: "Appearance",
      },
      {
        title: "Family Tree",
        artist: Groups.HarlotsProgressPresents,
        year: 2020,
        image: "/discog-images/family-tree.jpg",
        format: "File, FLAC, Single",
        label: "Not On Label",
        role: "Appearance",
      },
      {
        title: "Heavenly Spring",
        artist: Groups.YMIAH,
        year: 2020,
        image: "/discog-images/heavenly-spring.jpg",
        format: "File, MP3, EP",
        label: "Not On Label",
        role: "Appearance",
      },
      {
        title: "Laughing in My Sleep",
        artist: Groups.RodSherwood,
        year: 2019,
        image: "/discog-images/laughing-in-my-sleep.jpg",
        format: "File, MP3, Album",
        label: "Not On Label",
        role: "Appearance",
      },
      {
        title: "The Obleeks Live at VCR Chicago",
        artist: Groups.TheObleeks,
        year: 2018,
        image: "/discog-images/live-at-the-vcr.jpg",
        format: "File, MP3, Album",
        label: "Not On Label",
        role: "Appearance",
      },
      {
        title: "Satisfaction-promise",
        artist: Groups.MOONER,
        year: 2018,
        image: "/discog-images/satisfaction-promise.jpg",
        role: "Appearance",
      },
      {
        title: "The Obleeks",
        artist: Groups.TheObleeks,
        year: 2017,
        image: "/discog-images/the-obleeks-album.jpg",
        format: "LP, Album",
        label: "Good Land Records",
        role: "Appearance",
      },
      {
        title: "Potential",
        artist: Groups.Peasantry,
        year: 2017,
        image: "/discog-images/potential.jpg",
        format: "File, MP3, MiniAlbum, EP",
        label: "Not On Label",
        role: "Appearance",
      },
      {
        title: "& Hunnybear Vol. I",
        artist: Groups.LukeHenry,
        year: 2017,
        image: "/discog-images/and-hunnybear.jpg",
        format: "File, MP3, MiniAlbum, EP",
        label: "Not On Label",
        role: "Appearance",
      },
      {
        title: "Hiatus EP",
        artist: Groups.TheKuhls,
        year: 2016,
        image: "/discog-images/hiatus-ep.jpg",
        format: "File, MP3, EP",
        label: "Not On Label",
        role: "Appearance",
      },
      {
        title: "Cleaning Out My Head // Movies",
        artist: Groups.LukeHenry,
        year: 2016,
        image: "/discog-images/cleaning-out-my-head.jpg",
        format: "File, MP3, Single",
        label: "Not On Label",
        role: "Appearance",
      },
      {
        title: "Fire and Ice EP",
        artist: Groups.VILΛS,
        year: 2016,
        image: "/discog-images/fire-and-ice-ep.jpg",
        format: "File, MP3, EP",
        label: "Not On Label",
        role: "Appearance",
      },
      {
        title: "American Dreams",
        artist: Groups.LukeHenryAndRabbitfoot,
        year: 2015,
        image: "/discog-images/american-dreams.jpg",
        format: "LP, Album, S/Edition, Ear",
        label: "Not On Label",
        role: "Appearance",
      },
      {
        title: "Peasanté",
        artist: Groups.Peasantry,
        year: 2015,
        image: "/discog-images/pesante.jpg",
        format: "Cass + File, MP3",
        label: "Not On Label",
        role: "Appearance",
      },
      {
        title: "In Love / With Love",
        artist: Groups.SonsOfTheWest,
        year: 2015,
        image: "/discog-images/in-love-with-love.jpg",
        format: "Cass + File, MP3",
        label: "Not On Label",
        role: "Appearance",
      },
      {
        title: "One in a Million",
        artist: Groups.TheObleeks,
        year: 2015,
        image: "/discog-images/one-in-a-million.jpg",
        format: "File, MP3, EP",
        label: "Not On Label",
        role: "Appearance",
      },
      {
        title: "Palace",
        artist: Groups.Peasantry,
        year: 2014,
        image: "/discog-images/palace.jpg",
        format: "File, MP3, EP",
        label: "Not On Label",
        role: "Appearance",
      },
      {
        title: " I Will Never Be Your Friend (A Shot in the Back)",
        artist: Groups.SonsOfTheWest,
        year: 2012,
        image: "/discog-images/never-be-your-friend.jpg",
        format: "File, MP3",
        label: "Not On Label",
        role: "Appearance",
      },
      {
        title: "Sons of the West",
        artist: Groups.SonsOfTheWest,
        year: 2010,
        image: "/discog-images/sonsofthewest-1.jpg",
        format: "9xFile, MP3",
        label: "Not On Label",
        role: "Appearance",
      }
    ]
  },
  {
    creditedAs: "Ricky Mirage",
    releases: [
      {
        title: "Degeneration b​/​w Doomsday Clock",
        artist: Groups.RickyMirage,
        year: 2022,
        image: "/discog-images/doomsday-clock.jpg",
        format: "File, MP3, Single",
        label: "Mother Fungus Records",
        role: "Main",
      },
      {
        title: "hope and hindsight",
        artist: Groups.RickyMirage,
        year: 2018,
        image: "/discog-images/hope-and-hindsight.jpg",
        format: "File, MP3, EP",
        label: "Mother Fungus Records",
        role: "Main",
      },
      {
        title: "I can't believe it's Christmas",
        artist: Groups.RickyMirage,
        year: 2017,
        image: "/discog-images/christmas.jpg",
        format: "File, MP3, Single",
        label: "Mother Fungus Records",
        role: "Main",
      },
      {
        title: "fistful of metal b​/​w shadow of doubt",
        artist: Groups.RickyMirage,
        year: 2017,
        image: "/discog-images/fistful.jpg",
        format: "File, MP3, Single",
        label: "Mother Fungus Records",
        role: "Main",
      },
      {
        title: "manic romantic",
        artist: Groups.RickyMirage,
        year: 2016,
        image: "/discog-images/manic%20romantic.jpg",
        format: "File, MP3, Album + Cass, Album",
        label: "Mother Fungus Records, Athletic Tapes",
        role: "Main",
      },
      {
        title: "with love",
        artist: Groups.RickyMirage,
        year: 2016,
        image: "/discog-images/with-love.jpg",
        format: "File, MP3, Single",
        label: "Mother Fungus Records",
        role: "Main",
      },
      {
        title: "pop goes the sun",
        artist: Groups.RickyMirage,
        year: 2015,
        image: "/discog-images/pop-goes-the-sun.jpg",
        format: "File, MP3, Album",
        label: "Mother Fungus Records",
        role: "Main",
      },
      {
        title: "holiday bonus",
        artist: Groups.RickyMirage,
        year: 2014,
        image: "/discog-images/holiday-bonus.jpg",
        format: "File, MP3, Single",
        label: "Mother Fungus Records",
        role: "Main",
      },
      {
        title: "night terrors",
        artist: Groups.RickyMirage,
        year: 2014,
        image: "/discog-images/night-terrors.jpg",
        format: "File, MP3, MiniAlbum",
        label: "Mother Fungus Records",
        role: "Main",
      },
      {
        title: "do it yourself help book",
        artist: Groups.RickyMirage,
        year: 2014,
        image: "/discog-images/do-it-yourself-helpbook.jpg",
        format: "File, MP3, MiniAlbum, EP",
        label: "Mother Fungus Records",
        role: "Main",
      },
      {
        title: "goodnight, morning",
        artist: Groups.RickyMirage,
        year: 2014,
        image: "/discog-images/goodnight-morning.jpg",
        format: "File, MP3, MiniAlbum",
        label: "Mother Fungus Records",
        role: "Main",
      }
    ]
  }
];
