module.exports = {
  content: ["./pages/**/*.tsx", "./components/**/*.tsx"],
  theme: {
    colors: {
      transparent: "transparent",
      black: "#000",
      white: "#fff",
      50: "var(--color-base-50)",
      100: "var(--color-base-100)",
      200: "var(--color-base-200)",
      300: "var(--color-base-300)",
      400: "var(--color-base-400)",
      500: "var(--color-base-500)",
      600: "var(--color-base-600)",
      700: "var(--color-base-700)",
      800: "var(--color-base-800)",
      900: "var(--color-base-900)",
      primary: {
        50: "var(--color-primary-50)",
        100: "var(--color-primary-100)",
        200: "var(--color-primary-200)",
        300: "var(--color-primary-300)",
        400: "var(--color-primary-400)",
        DEFAULT: "var(--color-primary)",
        500: "var(--color-primary-500)",
        600: "var(--color-primary-600)",
        700: "var(--color-primary-700)",
        800: "var(--color-primary-800)",
        900: "var(--color-primary-900)",
      },
      secondary: {
        50: "var(--color-secondary-50)",
        100: "var(--color-secondary-100)",
        200: "var(--color-secondary-200)",
        300: "var(--color-secondary-300)",
        400: "var(--color-secondary-400)",
        DEFAULT: "var(--color-secondary)",
        500: "var(--color-secondary-500)",
        600: "var(--color-secondary-600)",
        700: "var(--color-secondary-700)",
        800: "var(--color-secondary-800)",
        900: "var(--color-secondary-900)",
      },
      surface: {
        300: "var(--color-surface-300)",
        400: "var(--color-surface-400)",
        DEFAULT: "var(--color-surface)",
        500: "var(--color-surface-500)",
        600: "var(--color-surface-600)",
        700: "var(--color-surface-700)",
      },
      interaction: {
        400: "var(--color-interaction-400)",
        DEFAULT: "var(--color-interaction-500)",
        500: "var(--color-interaction-500)",
        600: "var(--color-interaction-600)",
      },
      background: "var(--color-background)",
      accent: "var(--color-accent)",
      success: {
        100: "var(--color-success-100)",
        DEFAULT: "var(--color-success)",
      },
      info: "var(--color-info)",
      warning: "var(--color-warning)",
      error: {
        100: "var(--color-error-100)",
        DEFAULT: "var(--color-error)",
      },
      pending: "var(--color-pending)",
      placeholder: "var(--color-placeholder)",
      photo: "var(--color-photo-background)",
      green: "#40bb72",
    },
    spacing: {
      px: "1px",
      0: "0",
      0.5: "var(--spacer-0_5)",
      1: "var(--spacer-1)",
      1.5: "var(--spacer-1_5)",
      2: "var(--spacer-2)",
      2.5: "var(--spacer-2_5)",
      3: "var(--spacer-3)",
      3.5: "var(--spacer-3_5)",
      4: "var(--spacer-4)",
      4.5: "var(--spacer-4_5)",
      5: "var(--spacer-5)",
      5.5: "var(--spacer-5_5)",
      6: "var(--spacer-6)",
      6.5: "var(--spacer-6_5)",
      7: "var(--spacer-7)",
      7.5: "var(--spacer-7_5)",
      8: "var(--spacer-8)",
      8.5: "var(--spacer-8_5)",
      9: "var(--spacer-9)",
      9.5: "var(--spacer-9_5)",
      10: "var(--spacer-10)",
      11: "var(--spacer-11)",
      12: "var(--spacer-12)",
      14: "var(--spacer-14)",
      16: "var(--spacer-16)",
      18: "var(--spacer-18)",
      20: "var(--spacer-20)",
      22: "var(--spacer-22)",
      24: "var(--spacer-24)",
      32: "var(--spacer-32)",
      36: "var(--spacer-36)",
      40: "var(--spacer-40)",
      48: "var(--spacer-48)",
      56: "var(--spacer-56)",
      64: "var(--spacer-64)",
      72: "var(--spacer-72)",
      80: "var(--spacer-80)",
      90: "var(--spacer-90)",
      100: "var(--spacer-100)",
      110: "var(--spacer-110)",
      120: "var(--spacer-120)",
    },
    borderColor: (theme) => ({
      ...theme("colors"),
      DEFAULT: "var(--color-border, currentColor)",
    }),
    borderRadius: {
      none: "0",
      sm: "var(--border-radius-sm)",
      DEFAULT: "var(--border-radius-default)",
      lg: "var(--border-radius-lg)",
      xl: "var(--border-radius-xl)",
      full: "9999px",
    },
    boxShadow: {
      xs: "0 0 0 1px rgba(0, 0, 0, 0.05)",
      sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
      DEFAULT:
        "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)",
      md: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)",
      lg: "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)",
      xl: "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)",
      "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
      inner: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)",
      outline: "0 0 0 3px rgba(66, 153, 225, 0.5)",
      none: "none",
    },
    fill: (theme) => ({
      ...theme("colors"),
      current: "currentColor",
    }),
    fontFamily: {
      sans: "var(--font-family-sans)",
      serif: "var(--font-family-serif)",
      mono: "var(--font-family-mono)",
    },
    fontSize: {
      xs: ["var(--font-size-xs)", "var(--line-height-relaxed)"],
      sm: ["var(--font-size-sm)", "var(--line-height-normal)"],
      base: ["var(--font-size-base)", "var(--line-height-normal)"],
      lg: ["var(--font-size-lg)", "var(--line-height-normal)"],
      xl: ["var(--font-size-xl)", "var(--line-height-snug)"],
      "2xl": ["var(--font-size-2xl)", "var(--line-height-snug)"],
      "3xl": ["var(--font-size-3xl)", "var(--line-height-tight)"],
      "4xl": ["var(--font-size-4xl)", "var(--line-height-tight)"],
      "5xl": ["var(--font-size-5xl)", "var(--line-height-tight)"],
      "6xl": ["var(--font-size-6xl)", "var(--line-height-tight)"],
    },
    letterSpacing: {
      tighter: "var(--letter-spacing-tighter)",
      tight: "var(--letter-spacing-tight)",
      normal: "0",
      wide: "var(--letter-spacing-wide)",
      wider: "var(--letter-spacing-wider)",
      widest: "var(--letter-spacing-widest)",
    },
    lineHeight: {
      none: "1",
      tight: "var(--line-height-tight)",
      snug: "var(--line-height-snug)",
      normal: "var(--line-height-normal)",
      relaxed: "var(--line-height-relaxed)",
      loose: "var(--line-height-loose)",
      3: ".75rem",
      4: "1rem",
      5: "1.25rem",
      6: "1.5rem",
      7: "1.75rem",
      8: "2rem",
      9: "2.25rem",
      10: "2.5rem",
    },
    stroke: (theme) => ({
      ...theme("colors"),
      current: "currentColor",
    }),
    extend: {
      borderWidth: {
        3: "3px",
        6: "6px",
      },
      flexGrow: {
        "1/2": 0.5,
        "3/4": 0.75,
        2: 2,
      },
      inset: (theme) => ({
        ...theme("spacing"),
        "-0.5": "calc(var(--spacer-0_5) * -1)",
        "1/2": "50%",
        "122px": "122px",
      }),
      maxHeight: (theme) => ({
        ...theme("spacing"),
        none: "none",
      }),
      maxWidth: (theme) => ({
        ...theme("spacing"),
        0: "0",
        screen: "100vw",
        "screen-xs": "var(--screen-xs)",
        "screen-sm": "var(--screen-sm)",
        "screen-md": "var(--screen-md)",
        "screen-lg": "var(--screen-lg)",
        "screen-xl": "var(--screen-xl)",
        "screen-2xl": "var(--screen-2xl)",
      }),
      minHeight: (theme) => ({
        ...theme("spacing"),
      }),
      minWidth: (theme) => ({
        ...theme("spacing"),
        80: "var(--spacer-80)",
      }),
      zIndex: {
        1: "1",
      },
    },
  },
  plugins: [],
};
