import type { GetStaticProps } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { getSortedProjectsData } from '../lib/projects'
import { AllProjectsData } from '../domain/props.interface'


export default function Home({
  allProjectsData
}: {
  allProjectsData: AllProjectsData[]
}){
  return (
    <div className={styles.container}>
      <Head>
        <title>Nick Harris</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.89em%22 font-size=%22100%22>🧑🏻‍💻</text></svg>"
        />
        <script src="https://kit.fontawesome.com/7b5f7f4b99.js"></script>
      </Head>

      <main className={styles.main}>
        {/* top section */}
        <h1 className={styles.title}>
          Nick Harris
        </h1>
        {/* bio */}
        <p className={styles.description}>
          I'm a Chicago-based web developer currently working on the front end at Rheaply. I'm also a multi-instrumentalist singer/songwriter. Whether it's a album or a web application, I love building things.
        </p>
        {/* links */}
        <p className={styles.description}>
          Let's connect!
        </p>
        <div className="flex">
          <a href="https://www.linkedin.com/in/nick-harris-web-dev/" rel="noreferrer" aria-label="Linked In" className="no-underline" target="_blank">
            <i className="fab fa-linkedin fa-3x mr-2 text-primary-500"></i>
          </a>
          <a href="https://www.github.com/nickharrisdev" className="no-underline" target="_blank" rel="noreferrer" aria-label="Github">
            <i className="fab fa-github fa-3x mx-2 text-primary-500"></i>
          </a>
          <a href="https://fosstodon.org/@nickharris" className="no-underline" target="_blank" rel="noreferrer" aria-label="Mastadon">
            <i className="fab fa-mastodon fa-3x mx-2 text-primary-500"></i>
          </a>
          <a href="mailto:nick@nickharris.me" className="no-underline" target="_blank" rel="noreferrer" aria-label="Email">
            <i className="far fa-envelope fa-3x mx-2 text-primary-500"></i>
          </a>
      </div>
        {/* section with icons as links */}
        <Link href="/music">
          <a>My music</a>
        </Link>
        {/* projects list */}
        <ul>
          {allProjectsData.map(({ id, date, title }) => (
            <li key={id}>
              {title}
              <br />
              {id}
              <br />
              {date}
            </li>
          ))}
        </ul>
      </main>

      {/* <footer className={styles.footer}>
      </footer> */}
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const allProjectsData = getSortedProjectsData()
  return {
    props: {
      allProjectsData
    }
  }
}