import type { GetStaticProps } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import { getSortedProjectsData } from '../lib/projects'
import { AllProjectsData } from '../domain/props.interface'


export default function Home({
  allProjectsData
}: {
  allProjectsData: AllProjectsData[]
}){
  return (
    <div className={styles.container}>
      <Head>
        <title>Nick Harris</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.89em%22 font-size=%22100%22>🧑🏻‍💻</text></svg>"
        />
      </Head>

      <main className={styles.main}>
        {/* top section */}
        <div className={styles.titleSummaryContainer}>
          <h1>
            Nick Harris
          </h1>
          <p>
            Web developer | Musician
          </p>
          <p>
            Chicago, Illinois
          </p>
        </div>

        {/* nav */}
        <nav className={styles.nav}>
          {/* projects */}
          <a href="#projects">Projects</a>
          {/* discography */}
          <Link href="/discography">
            <a>Discography</a>  
          </Link>
          {/* contact */}
          <a href="#contact">Contact</a>
        </nav>
      
        {/* projects list */}
        <h2 id="projects">
          Projects
        </h2>
        <ul>
          {allProjectsData.map(({ id, date, title }) => (
            <li key={id}>
              {title}
              <br />
              {id}
              <br />
              {date}
            </li>
          ))}
        </ul>

        {/* links */}
        <div id="contact" className={styles.contactIconsContainer}>
          <h2>Get in touch</h2>
          <a href="https://www.linkedin.com/in/nick-harris-web-dev/" rel="noreferrer" aria-label="Linked In" className="no-underline" target="_blank">
            <i className="fab fa-linkedin fa-3x mr-2 text-primary-500"></i>
          </a>
          <a href="https://www.github.com/nickharrisdev" className="no-underline" target="_blank" rel="noreferrer" aria-label="Github">
            <i className="fab fa-github fa-3x mx-2 text-primary-500"></i>
          </a>
          <a href="https://fosstodon.org/@nickharris" className="no-underline" target="_blank" rel="noreferrer" aria-label="Mastadon">
            <i className="fab fa-mastodon fa-3x mx-2 text-primary-500"></i>
          </a>
          <a href="mailto:nick@nickharris.me" className="no-underline" target="_blank" rel="noreferrer" aria-label="Email">
            <i className="far fa-envelope fa-3x mx-2 text-primary-500"></i>
          </a>
        </div>  
      </main>

      {/* <footer className={styles.footer}>
      </footer> */}
      {/* @ts-ignore */}
           <script src="https://kit.fontawesome.com/7b5f7f4b99.js" defer="defer"></script>
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const allProjectsData = getSortedProjectsData()
  return {
    props: {
      allProjectsData
    }
  }
}