import type { GetStaticProps } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getSortedProjectsData } from '../lib/projects'
import { AllProjectsData } from '../domain/props.interface'
import useSWR from 'swr'

const fetcher = (url: string) => fetch(url).then((res) => res.json());

export default function Music({
  allProjectsData
}: {
  allProjectsData: AllProjectsData[]
}){
  // need to use this combination of urls to get all the data needed from discogs.
  // first get releases of mine, then get more data about those releases for specifcs about my role
  // might be a good usecase for promise.all, but unsure why SWR doesn't use promises
  // todo: move this func to another section of the app to handle data getting
  // https://api.discogs.com/artists/6067515
  // https://api.discogs.com/artists/6067515/releases
  const { data, error } = useSWR(
    "https://api.discogs.com/releases/15698926",
    fetcher
  );
  console.log(data, error, "response")
  // &key=foo123&secret=bar456"
  // if (error) return "An error has occurred.";
  // if (!data) return "Loading...";
  return (
    <div className={styles.container}>
      <Head>
        <title>Music | Nick Harris</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.89em%22 font-size=%22100%22>🧑🏻‍💻</text></svg>"
        />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Music
        </h1>
      </main>

      {/* <footer className={styles.footer}>
      </footer> */}
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const allProjectsData = getSortedProjectsData()
  return {
    props: {
      allProjectsData
    }
  }
}