import type { GetStaticProps } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { getSortedProjectsData } from '../lib/projects'
import { AllProjectsData } from '../domain/props.interface'

export default function Home({
  allProjectsData
}: {
  allProjectsData: AllProjectsData[]
}){
  return (
    <div className={styles.container}>
      <Head>
        <title>Nick Harris</title>
        <meta name="description" content="Generated by create next app" />
        <link
      rel="icon"
      href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.89em%22 font-size=%22100%22>🧑🏻‍💻</text></svg>"
    />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Music!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
        <ul>
          {allProjectsData.map(({ id, date, title }) => (
            <li key={id}>
              {title}
              <br />
              {id}
              <br />
              {date}
            </li>
          ))}
        </ul>
      </main>

      {/* <footer className={styles.footer}>
      </footer> */}
    </div>
  )
}

export const getStaticProps: GetStaticProps = async () => {
  const allProjectsData = getSortedProjectsData()
  return {
    props: {
      allProjectsData
    }
  }
}